### ISSUE TITLE
Update Uzbekistan list.

### ISSUE THREAD

**Issue by aelloc** [lauripiispanen/most-active-github-users-counter#187] opened 2023-02-20 13:44 UTC
I'm waiting for the update for a week xD

**Comment by ashkulz** [comment] 2023-02-26 09:10
Duplicate of #170, see [this comment for details](https://github.com/lauripiispanen/most-active-github-users-counter/issues/98#issuecomment-1147468878) :man_shrugging:

**Closed as completed** 2023-02-26 09:30 UTC
