### ISSUE TITLE
Bug in (1366x768) screen [Site]

### ISSUE THREAD

**Issue by scarletquasar** [lauripiispanen/most-active-github-users-counter#143] opened 2021-11-30 16:20 UTC
https://imgur.com/a/uIBFTmZ

Mouse over the project maintainer link is reorganizing the screen in a weird way. Page: (https://commits.top/)

**Comment by ashkulz** [comment] 2021-12-26 06:40
I think this is a duplicate of lauripiispanen/github-top#212

**Comment by ashkulz** [comment] 2022-01-03 07:59
@EternalQuasar0206 can you check if this is an issue with [my fork](https://github.com/ashkulz/committers.top#why-is-this-running-on-a-different-domain)?

**Comment by scarletquasar** [comment] 2022-01-03 11:10
> @EternalQuasar0206 can you check if this is an issue with [my fork](https://github.com/ashkulz/committers.top#why-is-this-running-on-a-different-domain)?

Looks like it's solved, can't find the bug anymore in the page

**Closed as completed** 2022-06-18 02:06 UTC
