### ISSUE TITLE
Country Senegal not showing

### ISSUE THREAD

**Issue by dofbi** [lauripiispanen/most-active-github-users-counter#184] opened 2022-12-15 20:56 UTC
Hello 
Just visited this page https://commits.top/senegal.html
No Data
![Capture d’écran du 2022-12-15 20-55-34](https://user-images.githubusercontent.com/84446/207965315-84b4a363-9e85-4581-85af-3feb55eb59ca.png)

**Comment by ashkulz** [comment] 2022-12-19 04:15
Duplicate of #170, see [this comment for details](https://github.com/lauripiispanen/most-active-github-users-counter/issues/98#issuecomment-1147468878) :man_shrugging:

**Comment by dofbi** [comment] 2022-12-21 22:27
Thanks you

**Closed as completed** 2022-12-21 22:27 UTC
